complete hw "Object method"
kosmosensei/hw10 pull request #2
Opened 2023-03-24 19:48 UTC by kosmosensei

2023-03-25 11:21 UTC, safgbad requested changes

2023-03-25 11:21 UTC, safgbad commented on src/pro/sky/java/course1/lesson1/Author.java
> +        }
метод должен называться equals, ничего лишнего в названии не должно быть

если в этот метод придет null в качестве аргумента (other == null), то программа выкинет NullPointerException и не сработает корректно
чтобы этого избежать нужно сначала проверить other на null:
```java
if (other == null || this.getClass() != other.getClass()) {
    return false;
}
```

2023-03-25 11:21 UTC, safgbad commented on src/pro/sky/java/course1/lesson1/Author.java
> +    }
в контексте программы авторы "Александр Пушкин" и "Александр Солженицын" будут эквивалентны, так как в equals сравниваются только имена авторы, а фамилии не участвуют в сравнении

нужно сравнивать и имена, и фамилии

2023-03-25 11:21 UTC, safgbad commented on src/pro/sky/java/course1/lesson1/Author.java
> +    }
хеш-код должен генерироваться в соответствии с equals:
```java
return Objects.hash(firstName, lastName);
```

2023-03-25 11:21 UTC, safgbad commented on src/pro/sky/java/course1/lesson1/Book.java
> +    }
toString должен возвращать строку, которая полностью характеризует объект
тут возвращается только лишь информация о годе публикации, а нужно еще в эту строку поместить информацию об авторе и названии книги

2023-03-25 11:21 UTC, safgbad commented on src/pro/sky/java/course1/lesson1/Book.java
> +    }
здесь проблемы аналогичные тем, что были в Author

2023-03-25 11:52 UTC, kosmosensei commented on src/pro/sky/java/course1/lesson1/Author.java
> +    }
Да, так как и была данная задумка :)

2023-03-26 15:18 UTC, safgbad requested changes

2023-03-26 15:18 UTC, safgbad commented on src/pro/sky/java/course1/lesson1/Author.java
> +    }
интересное решение сравнивать текстовое представление объекта)

все-таки обычно пишут как-то так:
```java
return Objects.equals(firstName, firstName2.firstName)
    && Objects.equals(lastName, firstName2.lastName);
```
легче будет воспринимать, если объект, лежащий сейчас в firstName2, будет лежать в переменной с названием author:
```java
Author author = (Author) other;
```
все-таки это не только имя, а целый автор)

2023-03-26 15:18 UTC, safgbad commented on src/pro/sky/java/course1/lesson1/Book.java
> +        if (other.getClass() != this.getClass()) {
метод должен называться просто equals

2023-03-26 15:18 UTC, safgbad commented on src/pro/sky/java/course1/lesson1/Book.java
> +    }
тут снова может возникнуть какая-то путаница
лучше использовать не name, а book:
```java
Book book = (Book) other;
```
судя по коду, который есть сейчас все книги одного автора будут эквивалентны между собой, нужно сравнивать не только автора , но и название:
```java
return Objects.equals(name, book.name)
    && Objects.equals(author, book.author);
```
а хеш код должен генерироваться в соответствии с написанным equals, то есть нужно туда будет засунуть и name, и author:
```java
return Objects.hash(name, author);
```

2023-03-27 16:56 UTC, safgbad approved these changes

2023-03-28 05:50 UTC, merged